# Generated by Django 5.0.3 on 2024-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="status",
            field=models.BooleanField(default=False, verbose_name="estado"),
        ),
    ]
